### ISSUE TITLE
inconsistent use of section markers

### ISSUE THREAD

**Issue by DrGo** [citation-style-language/test-suite#11]
Hello,
I am writing a CSL processor in Go (https://github.com/DrGo/csl) and wrote a simple tool to process the test fixture files.
I noticed inconsistent use of markers in the file magic_SecondFieldAlign.txt, so  there is 
`>>== MODE ==>>`
but 
`>>===== CSL =====>>`
Is this a bug in the file or are both version permitted?

Thanks,

/salah

**Comment by fbennett** [comment]
The fixture format isn't at all pretty. :-( Here are the regexps that I use to snip out the blocks, which is forgiving of sloppiness in the markup:
```
openRex = new RegExp("^.*>>===*\\s(" + Object.keys(sections).join("|") + ")\\s.*=>>.*");
closeRex = new RegExp("^.*<<===*\\s(" + Object.keys(sections).join("|") + ")\\s.*=<<.*");
```

**Comment by bdarcus** [comment]
Can we close this now?

**Comment by DrGo** [comment]
Yes
It sounds they are permitted
