### ISSUE TITLE
The abbreviations section is not described

### ISSUE THREAD

**Issue by ndw** [citation-style-language/test-suite#14]
Neither the spec nor the test-suite documentation appear to describe how the abbreviations section applies. For example, in `condition_IsNumeric.txt`:
```
>>===== ABBREVIATIONS =====>>
{
    "default": {
        "number": {
            "2nd volume": "2ND"
        }
    }
}
<<===== ABBREVIATIONS =====<<
```

**Comment by bdarcus** [comment]
Flagging this for a few people, since it bears on the clarity of the spec. Would be nice if we could plug these holes are Norm is identifying them, and we're working on resolving lingering issues on the schema.

@rmzelle @adam3smith @bwiernik @denismaier

**Comment by ndw** [comment]
Also appearing in tests but not described in the test-suite documentation: DESCRIPTION, LANGPARAMS, MULTIAFFIX, and OPTIONS

Also, BIBSECTION which is described does not appear in any tests.

**Comment by rmzelle** [comment]
I think these abbreviations are a `citeproc-js`-specific extension of CSL (this test-suite repo was created by citeproc-js/Juris-M creator @fbennett). See also https://juris-m.readthedocs.io/en/latest/abbrevs.html.

**Comment by bdarcus** [comment]
So we should thus remove them @rmzelle?

**Comment by denismaier** [comment]
Wait, `pandoc-citeproc` is uses abbreviations as well (see [here](chttps://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md)). 
Also, there's been some discussion to extend [abbreviations support](https://forums.zotero.org/discussion/75788/distributing-custom-abbreviations-file) with Zotero.

**Comment by bdarcus** [comment]
Maybe we need a PR to add this to the spec, then?

And in the meantime, move it to another directory?

**Comment by fbennett** [comment]
@ndw 
> Also appearing in tests but not described in the test-suite documentation: DESCRIPTION, LANGPARAMS, MULTIAFFIX, and OPTIONS

Tests that used the last three have been removed from the repo. The first element has been removed from the one test that remained (https://github.com/citation-style-language/test-suite/commit/def009c50bfc4bc6865104ce782e15f7d6dd436a)
