### ISSUE TITLE
Several tests use undocumented modes

### ISSUE THREAD

**Issue by ndw** [citation-style-language/test-suite#16]
Several tests have modes that are not described in the documentation: `bibliography-header` (`bibheader_EntryspacingDefaultValueOne`, `bibheader_EntryspacingExplicitValueZero`, `bibheader_SecondFieldAlign`, `bibheader_SecondFieldAlignWithAuthor`, `bibheader_SecondFieldAlignWithNumber`), `citation-rtf` (`bugreports_NonBreakingSpaceJoinFail`) and `bibliography-nosort` (`sort_BibliographyNosortOption`)

**Comment by bdarcus** [comment]
Norm - trying to put in something helpful to address these immediately, without really knowing anything about the test suite, 

I've added this PR which adds a list of tests to ignore from the citeproc-rs project, which is the most recent full-blown CSL implementation, and is intended to supercede citeproc-js. 

That list already had most of the tests you list here, except for two, which I just added.

Sorry for the hassle, and thanks for taking the time to report these.

https://github.com/citation-style-language/test-suite/pull/18

**Comment by jgm** [comment]
I was wondering about these, so I'm glad you're documenting them.

**Comment by bdarcus** [comment]
The PR basically removes them from the test suite, as generated by
processor.py.

Do you have any view on that as a solution, vs the ignore.txt file?

**Comment by bdarcus** [comment]
Nevermind; Frank is going to remove them entirely.
