### ISSUE TITLE
Item type film in bugreports_MissingItemInJoin

### ISSUE THREAD

**Issue by michel-kraemer** [citation-style-language/test-suite#2]
[`bugreports_MissingItemInJoin.txt#L292`](https://github.com/citation-style-language/test-suite/blob/master/processor-tests/humans/bugreports_MissingItemInJoin.txt#L292) uses the item type `film` which AFAIK does not comply with the standard. I'm wondering if this is the actual bug you want to test against or if this is just a mistake.

The reason why I'm asking this is that citeproc-java uses a Java enum for item types and `film` is not defined there, which leads to a failed test. If I replace `film` with `motion_picture` the test runs successfully.

What do you think about that?

**Comment by rmzelle** [comment]
@fbennett, could you take a look? Per http://docs.citationstyles.org/en/stable/specification.html#appendix-iii-types, this should presumably be "motion_picture"?

**Comment by fbennett** [comment]
Fixed. Sorry about the delay in responding.
