### ISSUE TITLE
Invalid csl in test suite

### ISSUE THREAD

**Issue by jgm** [citation-style-language/test-suite#22]
I noticed the following invalid CSL (no layout element under citation) in the test suite.  This breaks my parser.  Is it intentional?
```xml
  <citation>
      <text value="bogus"/>
    </citation>
```
This is in `date_RangeDelimiter.txt`.

**Comment by bdarcus** [comment]
Thanks John.

Should be fixed with the commit I just pushed.

I have to assume it was just an oversight.

**Comment by jgm** [comment]
Thanks.
