### ISSUE TITLE
Question about affix_WithCommas.txt

### ISSUE THREAD

**Issue by jgm** [citation-style-language/test-suite#38]
Is the expected result for this test correct?
```
John Smith, <i>Book C</i>, 2000, and David Jones, <i>Book D</i>, 2000.
John Smith, <i>Book C</i>, 2000 is one source, David Jones, <i>Book D</i>, 2000 is another.
John Smith, <i>Book C</i>, 2000, 23 is one source, David Jones, <i>Book D</i>, 2000 is another.
```
I would have thought that in the second and third items, the short form of the names would be used because of
```
      <else-if position="subsequent">
          <group delimiter=", ">
            <text macro="contributors-short"/>
            <text macro="title-short"/>
            <text macro="point-locators-subsequent"/>
          </group>
        </else-if>
```
But maybe there's something I'm misunderstanding?
Isn't the criterion for "subsequent" met in this case?

**Comment by denismaier** [comment]
I'd also think that rendering according to `position="subsequent"` would be the expected behavior. I don't see why the full form should be used throughout. It's not only the names, also the year gets repeated in the second and third citation.

**Comment by bdarcus** [comment]
I've assigned this to Frank and Sebastian, and copying @cormacrelf if he has any thoughts.

**Comment by fbennett** [comment]
This is one of quite a few fixtures in which I lazily grabbed a full style for the CSL, and it's confusing here. The test was not intended to exercise position evaluation, and its input format (with CITATION-ITEMS) did not provide any context information. The processor was run in a mode that ignores implicit document context hints. I've changed the input format on the test to the full form (CITATIONS), and the processor now [spits out the short form of names in the subsequent references](https://github.com/citation-style-language/test-suite/blob/70ec5a75c90de560e2330e8177e30d50e9177a46/processor-tests/humans/affix_WithCommas.txt)

**Comment by bdarcus** [comment]
Thanks Frank!

**Comment by jgm** [comment]
Thank you!
