### ISSUE TITLE
Question about bugreports_SmallCapsEscape.txt

### ISSUE THREAD

**Issue by jgm** [citation-style-language/test-suite#42]
This is probably my own lack of understanding, but I'm confused about this test given what the spec says.
The test includes
``` xml
      <group display="left-margin">
        <text macro="date-bibliography" prefix=" "/>
        <date variable="original-date" prefix="[" suffix="]">
          <date-part name="year"/>
        </date>
      </group>
```
and the expected result suggests that this is supposed to render "N.d" (from the date-bibliography macro).  But I don't see how this is consistent with what the spec says about `group`, namely:

> cs:group implicitly acts as a conditional: cs:group and its child elements are suppressed if a) at least one rendering element in cs:group calls a variable (either directly or via a macro), and b) all variables that are called are empty. 

It seems to me that both a) and b) are true in this case.  a) at least one rendering element calls a variable -- e.g., the `date` element calls `original-date`.  b) all variables that are called are empty.

What am I missing?

**Comment by denismaier** [comment]
Good question. I think the current behavior is what you'd want here, but also don't see how this is consistent with the spec.
Perhaps @bwiernik @adam3smith @fbennett know more about this?

**Comment by bwiernik** [comment]
This was clarified in the spec in July:

> When a `cs:group` contains a child `cs:macro`, if the `cs:macro` is non-empty, it is treated as a non-empty variable for the purposes of determining suppression of the outer `cs:group`.

Using the no-date term in a macro is the main application of this rule.

**Comment by jgm** [comment]
Oh, I wish I'd known about that from the beginning! It will require some larger architectural changes to accommodate this.

**Comment by jgm** [comment]
The fix wasn't actually too hard. Thanks for the reply!

**Comment by bdarcus** [comment]
We should probably add this note to the test.

**Comment by bwiernik** [comment]
@jgm It's the same general thing we discussed in the open pull request about "encapsulating" macro behavior.
