### ISSUE TITLE
Delimiters in disambiguate_InitializeWithButNoDisambiguation

### ISSUE THREAD

**Issue by Jason-Abbott** [citation-style-language/test-suite#56]
I am stumped on [disambiguate_InitializeWithButNoDisambiguation](https://github.com/citation-style-language/test-suite/blob/48bacb1aa80b9ee1a12caf5ea9a7033946ed77d3/processor-tests/humans/disambiguate_InitializeWithButNoDisambiguation.txt). My result is 
```
(Doe, 1965a; 1965b)
```

but the expected result is
```
(Doe, 1965a, 1965b)
```

I am not seeing the setting that would override `<layout delimiter=“;”>` for use between the two citations — at least not in a way that still passes the other tests.

I think it must be simple but reading previous issues like https://github.com/citation-style-language/test-suite/issues/50 hasn’t turned on a lightbulb yet. This is the relevant content:

```xml
<citation et-al-min="4" et-al-use-first="3" disambiguate-add-year-suffix="true" collapse="year">
    <layout prefix="(" suffix=")" delimiter="; ">
        <group delimiter=", ">
            <text macro="author-short"/>
            <text macro="year-date"/>
            <group>
             <label variable="locator" suffix="*" form="short" strip-periods="true"/>
              <text variable="locator"/>
            </group>
          </group>
    </layout>
</citation>
```

```json
[
	{
		"author": [{ "family": "Doe", "given": "John" }],
		"id": "ITEM-1",
		"issued": { "date-parts": [["1965"]] },
		"title": "His Anonymous Life",
		"type": "book"
	},
	{
		"author": [{ "family": "Doe", "given": "Heroclitus" }],
		"id": "ITEM-2",
		"issued": { "date-parts": [["1965"]] },
		"title": "His Anonymous Second Life",
		"type": "chapter"
	}
]
```

**Comment by adam3smith** [comment]
That's actually speced: `cite-group-delimiter` defaults to `", "`

**Comment by Jason-Abbott** [comment]
Thank you, @adam3smith. That’s an easy change but it breaks at least one other test, [disambiguate_YearSuffixWithEtAlSubsequent](https://github.com/citation-style-language/test-suite/blob/2bea9caf5a3d04b3e68d4ecc8028c472a4499728/processor-tests/humans/disambiguate_YearSuffixWithEtAlSubsequent.txt).

If I have `cite-group-delimiter` default to `", "` _before_ using `<layout delimiter="; ">` then I get
```
(Smith 2000a, 2000b, 2000c)
```
for the first line of that test instead of what it expects,
```
(Smith 2000a; 2000b; 2000c)
```

The two test’s citation attributes look very similar (below). What I _do see_ is different is that one has `class="in-text”` citations and the other `class=“note”`. And if memory serves (I’ll go check now), that can magically change the `cite-group-delimiter` behavior.

<table>
  <tr>
   <td>
    <ul>
        <li> et-al-min="3"
        <li> et-al-use-first="1"
         <li>et-al-subsequent-min="3"
         <li>et-al-subsequent-use-first="1"
         <li>disambiguate-add-names="true"
         <li>disambiguate-add-year-suffix="true"
         <li>collapse=“year”
         <li>[layout delimiter]="; "
      </ul>
   </td>
   <td>
     <ul>
       <li>et-al-min=“4"
       <li> et-al-use-first=“3”
       <li></li>
       <li></li>
       <li></li>
       <li>disambiguate-add-year-suffix=“true"
      <li>collapse=“year"
      <li>[layout delimiter]="; "
     </ul>
</td></tr>
</table>

**Comment by Jason-Abbott** [comment]
There are probably enough delimiter threads out there. I’m happy to keep plugging along and figure it out. This is where I saw “in-text” might be relevant, though I’ve not bothered to full parse this section of code https://github.com/Juris-M/citeproc-js/blob/84a3916a20fc33ab53a2b57a8af1fe3b9d82452c/src/api_cite.js#L892

**Comment by Jason-Abbott** [comment]
Final note on this: I adjusted my code as follows and it’s passing both kinds of tests. Citations that are `in-text` use the default `“, “` if `cite-group-delimiter` isn’t set. Otherwise, the layout delimiter is tried first.

```swift
citationGroupingDelimiter
    ?? (placement == .inText
           ? CitationElement.defaultDelimiter
           : layout.delimiter ?? CitationElement.defaultDelimiter)

```

We’ll see how far this takes me 😄

**Comment by zepinglee** [comment]
Great! This solves my confusion.
