### ISSUE TITLE
Implicit sort in disambiguate_YearSuffixAndSort?

### ISSUE THREAD

**Issue by Jason-Abbott** [citation-style-language/test-suite#58]
The test [disambiguate_YearSuffixAndSort](https://github.com/citation-style-language/test-suite/blob/2bea9caf5a3d04b3e68d4ecc8028c472a4499728/processor-tests/humans/disambiguate_YearSuffixAndSort.txt) expects
```
1990m!; 1990l!; 1990k!; 1990j!; 1990i!; 1990h!; 1990g!; 1990f!; 1990e!; 1990d!; 1990c!; 1990b!; 1990a!
```
but I’m currently rendering
```
1990a!; 1990b!; 1990c!; 1990d!; 1990e!; 1990f!; 1990g!; 1990h!; 1990i!; 1990j!; 1990k!; 1990l!; 1990m!
```
The bibliography has a `<sort/>` element but citations do not, so I’m unclear why they should end up reversed.

**Comment by adam3smith** [comment]
The test is correct and directly follows spec.
There are two things working together:
1. From the specs: " The assignment of year-suffixes follows the order of the bibliographies entries" -- so given the titles of the items in the text suite, ambig-13 will be first in the bib and get 1990a and ambig-1 will get 1990m
2. Absent an explicit sort, items will be sorted in the order in which they're cited, which is ambig-1 first.

**Comment by Jason-Abbott** [comment]
Perhaps the explanation is [this Zotero comment](https://forums.zotero.org/discussion/comment/116235/#Comment_116235) from Frank:

> So to be clear, you want the year-suffix applied in each bibliography entry to be governed by the order in which the item is cited in the text, and not by the ordering in the bibliography? …. If so, that's not currently supported. 

I hadn’t noticed that rule before. That will solve it.

**Comment by Jason-Abbott** [comment]
@adam3smith Thank you! I just found that, though seeing it directly in the spec is better.
