### ISSUE TITLE
Difference between “noteIndex” and index of citation?

### ISSUE THREAD

**Issue by Jason-Abbott** [citation-style-language/test-suite#59]
I see in [position_ResetNoteNumbers](https://github.com/citation-style-language/test-suite/blob/2bea9caf5a3d04b3e68d4ecc8028c472a4499728/processor-tests/humans/position_ResetNoteNumbers.txt) that more than one citation (group of cite-items) can be assigned to a `noteIndex`. In that test, for example, “CITATION-3” and “CITATION-6” both end up with `noteIndex=3`. 

(For the sake of having all the tests pass, I’ve written a little citeproc-js [processCitationCluster()](https://citeproc-js.readthedocs.io/en/latest/running.html#processcitationcluster) mock that’s worked until now.)

My mental model has been that, for a note citation style, a citation _is_ a foot- or endnote. But apparently that isn’t so. I’m hoping someone can help me visualize what I would see on an actual page when more than one citation (group of cite-items) is in the same footnote — that should straighten out my semantics. 🙂

**Comment by bdarcus** [comment]
I think it's when you have multiple references in one citation, and hence also in its note?

Does that make sense?

**Comment by Jason-Abbott** [comment]
@bdarcus your answer was sensible but I decided to skip this test at the time until I could see other examples since what I saw suggested not just multiple references per citation (or cites per citation — however you want to say it) but also multiple citations (or citation groups) per note.

I think the test [position_IbidSeparateCiteSameNote](https://github.com/citation-style-language/test-suite/blob/c49f1f118e76db73241df8c7a9cba1e66a3b7b0b/processor-tests/humans/position_IbidSeparateCiteSameNote.txt#L4) makes that explicit. It expects 

```
..[0] [citation1-item1-note1] Appleton “Tom Swift and His Electric Runabout” (1910).
..[1] [citation2-item1-note2] ibid.
..[2] [citation3-item1-note2] ibid. page 33.
..[3] [citation4-item2-note3] Bloggs “A Very Short Book Indeed” (2012); [citation4-item1-note3] Appleton supra note 1.
..[4] [citation5-item1-note4] Appleton supra note 1 page 99.
..[5] [citation6-item1-note4] Appleton supra note 1.
>>[6] [citation7-item1-note4] ibid.
```
You can see notes may contain multiple citations and citations may contain multiple items.

I believe this is an artifact of the `citeproc-js` processor and not an expression of CSL so I’m really just offering some detail for posterity more than looking for clarification at this point.

If I use Zotero to add citations to a Google Document, for example, there are simply cite-items within notes. I see no concept of another level of grouping within a note (please correct me if I’m wrong).

I will comment further if I learn more. I had a look through [api_cite.js](https://github.com/Juris-M/citeproc-js/blob/master/src/api_cite.js) but it’s a little dense for easy perusal. If it seems important, I’ll look more closely.

**Comment by zepinglee** [comment]
> My mental model has been that, for a note citation style, a citation _is_ a foot- or endnote. But apparently that isn’t so.

My understanding of this kind of style is that a note can be cited item(s) or text mixed with citations (i.e., in the form of `<text> <citation> <text> <citation> ...`). Although the second form can be achieved by putting `<text>` in the `prefix`s or `suffix`s of cites, it's not flexible enough if the `<text>` is very long or contains formatting beyond CSL.

> I’m hoping someone can help me visualize what I would see on an actual page when more than one citation (group of cite-items) is in the same footnote — that should straighten out my semantics. 🙂

The following are two endnotes in Figure 14.2 in The Chicago Manual of Style.

<img width="516" alt="Screenshot 2023-09-21 at 12 27 43" src="https://github.com/citation-style-language/test-suite/assets/12290822/341d668e-18e5-4f22-b243-286c64456e55">

> If I use Zotero to add citations to a Google Document, for example, there are simply cite-items within notes. I see no concept of another level of grouping within a note (please correct me if I’m wrong).

I have not tried with Google Docs. But in MS Word with Zotero extension, one can insert citations into footnotes as well as other text.

**Comment by Jason-Abbott** [comment]
@zepinglee that helps a lot. Thank you.

I had previously imagined that such text would be captured as the `prefix` or `suffix` on a [cite-item](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cite-items). But if arbitrary text is allowed between cite-items in a footnote, _not_ captured as `prefix` or `suffix`, then the added layer of indirection is understandable.

For what it’s worth, Google Docs allows me to enter arbitrary text between cite-items in a footnote but the Zotero plugin will discard that text if the citation is updated.

<img width="617" alt="image" src="https://github.com/citation-style-language/test-suite/assets/6289308/a2150f1e-8e84-44be-aba9-7f6d23e08210">

**Comment by bdarcus** [comment]
> I had previously imagined that all such text would be captured as the `prefix` or `suffix` on a [cite-item](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cite-items), as you allude. But if not then the added layer of indirection is understandable.

Not sure if this helps understand the context, but ...

The (unwritten I suppose) requirement behind this is that it be possible to switch back-and-forth between note-based and in-text styles without modifying the source document.

I insisted on that for partly selfish reasons: I'm in a field that uses both, though mostly in-text author date.

Hence a distinction between citations within notes and automatically-noted citations.

The first is independent of citation style class, while the second is specific to note styles.

**Comment by Jason-Abbott** [comment]
I appreciate the feedback on this. It makes sense now. I also think being able to switch between in-line and notes is important so I’ll look to ensure I support that as well.

**Comment by Jason-Abbott** [comment]
Following up on the note below, for the sake of future searchers, the Google Docs Zotero plugin _does_ allow multiple groups of cites in a single footnote, without discarding arbitrary, intervening text, if the additional cites are inserted _from the footnote_ (as I believe **zeppinglee** was describing) rather than trying to manage them all from original footnote insertion in the main text — if that makes sense.
 
> For what it’s worth, Google Docs allows me to enter arbitrary text between cite-items in a footnote but the Zotero plugin will discard that text if the citation is updated.
> 
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/6289308/269713283-2717e859-dec5-42dd-9478-56eaeed25166.png">
> 
> **Update**: The plugin allows arbitrary text _before or after all_ the cite-items in a footnote to remain. Only text inserted between cite-items is discarded. I still don’t see a way in Google Docs to have multiple groups of cite-items in one footnote.
