### ISSUE TITLE
Why year sort does’t apply in sort_AguStyleReverseGroups

### ISSUE THREAD

**Issue by Jason-Abbott** [citation-style-language/test-suite#60]
This [test](https://github.com/citation-style-language/test-suite/blob/2bea9caf5a3d04b3e68d4ecc8028c472a4499728/processor-tests/humans/sort_AguStyleReverseGroups.txt) sorts references as follows (among others before and after these)
```
Smith, A. and C. Allen (2000)
Smith, A. and B. Frank (1995)
Smith, A. and B. Frank (1997)
```

I render that portion (the rest are the same) as
```
Smith, A. and B. Frank (1995)
Smith, A. and B. Frank (1997)
Smith, A. and C. Allen (2000)
```
due to
```xml
 <key macro="key-year" />
```

The full set of sort keys are
```xml
<key macro="key-creators" names-min="1" names-use-first="1" />
<key macro="key-creators-count" names-min="3" names-use-first="3" sort="descending" />
<key macro="key-creators" names-min="3" names-use-first="1" />
<key macro="key-year" />
```
Since these three references have the same name count and the same initial name for `names-use-first="1”`, it isn’t clear to my why the year sort _wouldn’t_ pertain.

I know … this looks simple enough that I’m likely overlooking something obvious 🙂

**Comment by adam3smith** [comment]
There are only two authors, so names-min=3 doesn't kick in for the 3rd sort
condition and it sorts by the 2nd author (that sort combination is actually
fairly common in the 'wild')

**Comment by bdarcus** [comment]
As I'm working on my project, is this kind of flexibility necessary?

My thought is sorting is independent of display (including contributor list shortening), so it's reasonable to just do:

```yaml
sort:
  - key: author
    order: ascending 
  - key: year
    order: ascending
```

Is that a reasonable assumption?

If it is, it makes things much simpler all around.

I had checked what was in the styles repo using ripgrep, and it seemed to be match what I saw.

**Comment by adam3smith** [comment]
No, as I say, the above combination of four conditions, a mix of author
count and alphabetical, is required specifically in a number of styles and
was introduced in 1.0 to meet that need.

**Comment by bdarcus** [comment]
But it doesn't need to be handled with templates; does it?

Could the behavior not be configured with a parameter?

**Comment by adam3smith** [comment]
Sorry, I can't follow. I'm not clear what template or parameter means in this context (and am not even sure I know what 'it' refers to precisely).

**Comment by bdarcus** [comment]
Sorry for the confusion.

Template = macro call.

It = sorting behavior.

Parameter = in this case, configuring that behavior outside the details of how to render to an author name.

```yaml
sort:
  keyAsRendered: true
```

The above is just for illustration; I'm not sure I really understand the logic of that configuration vis-a-vis rendering.

Is all that example saying is sort the author key the same way you render the author it in the bibliography?

Why I asked.

@Jason-Abbott how do you actually code sorting conceptually?

**Comment by fbennett** [comment]
The special handling applied to a call to a cs:name element  via the
"macro" attribute on cs:key is spelled out in the specification in some
detail, along with the reasons for it.

https://docs.citationstyles.org/en/stable/specification.html#toc-entry-66

**Comment by bdarcus** [comment]
Thanks @fbennett.

But in this specific case, what is the logic?

Obviously it has something to do with the number of authors. So if a reference has five authors, the sort key is not the full list.

In that example, would the name shortening be the same as it would for rendering?

**Comment by fbennett** [comment]
Yes. That's what the specification says, and it's what the citeproc-js
processor is built to do.

**Comment by bdarcus** [comment]
Ok, so we should add a note to that effect to the test.

**Comment by fbennett** [comment]
Or just link to the specification, which controls the behavior and was
carefully edited by Rintze. The test could also be extended with a few
namesets over five names in length to illustrate that behavior, but without
a reference back to the controlling language, that might just add another
layer of complexity to a difficult test and make it even harder to figure
out.

**Comment by bdarcus** [comment]
Agreed.

The two can be complementary though:

The spec describes the general behavior, and the tests can also briefly explain the use cases behind them.

**Comment by bdarcus** [comment]
Interestingly, this is conceptually how `BibLaTeX` handles this case.

E.g. a flat list of sorting options, and an optional ability override shortening, which defaults to shortening rules for the author.

```yaml
sort:
  rules: nty
  shorten:
    min: 4
    take: 2
```

**Comment by fbennett** [comment]
By flat list, you mean there's just one set of sort parameters? If so, that
wouldn't be able to express the conditions imposed by AGU.

**Comment by bdarcus** [comment]
I mean they have codes like "abc" that then map to some sorting behavior.

It's just an input string, in other words, but the processing is as complex
as it needs to be.

**Comment by fbennett** [comment]
So either there would be a separate syntax to express sorting behavior
under arbitrary named rules, or the behavior of a each available rule would
be written into the specification.

**Comment by Jason-Abbott** [comment]
> There are only two authors, so names-min=3 doesn't kick in for the 3rd sort condition and it sorts by the 2nd author (that sort combination is actually fairly common in the 'wild')

Oh gosh, that was easy. Thank you. I had it coded right at the `<names/>` level but added some sort macro render caching lately that didn’t differentiate on sort key et-al values.

**Comment by adam3smith** [comment]
Since I think of this in terms of citation style requirements rather than abstractions, here's a typical set of rules [(from the SAGE Harvard style](https://uk.sagepub.com/sites/default/files/sage_harvard_reference_style_0.pdf)) on sorting rule above:

> - Single-author references in date order;
> - Two-author references in alphabetical order according to the second author’s name;
> - Et al. references in alphabetical order; in the event of more than one entry having the same
> date, they should be placed in alphabetical order of second (or third) author, and a, b, etc. must
> be inserted

(the last bullet is different from the sort above, but you get the sense). 

I'm also a bit confused by the repeated reference to sorting not being independent of display: the nice thing about the way this currently works is that it _can_ be independent, as it is in this case (none of the key macros used in sorting are used in display) but for many styles it *can* call up the same macros to use for sorting. These are then used with the useful shortcuts noted in the specs (all names in sort order, no labels, etc.). Making this available makes sorting simpler to do (most styles just sort by the author macro) and easier to get consistent during style creation. In addition, the specifications explain the benefits of being able to use macros for sorting at some length.

**Comment by Jason-Abbott** [comment]
> @Jason-Abbott how do you actually code that sorting conceptually?

@bdarcus This particular test sorts entirely on macros so the `<sort><key/></sort>` comparisons are blind to the details. That means the comparison is simple but there’s no upper bound on how complex the macros might be (just need to render the macro correctly).

Other commenters have already surpassed what else I might say conceptually.

At an _implementation_ level, I iterate over the sort keys, `switch` on its sort type, call a method specific to that sort type (such as sorting names or dates), and break the loop on the first non-equal result. Each method has whatever parameters are needed to implement various rules — straight-forward, I think.

**Comment by bdarcus** [comment]
The examples they include seem to suggest pretty standard author-year?

```
Brown J (2003)
Brown TR and Yates P (2003)
Brown W (2002)
Brown W (2003a)
Brown W (2003b)
Brown W and Jones M (2003)
Brown W and Peters P (2003)
Brown W, Hughes J and Kent T (2003a)
Brown W, Kent T and Lewis S (2003b)
```

> the specifications explain the benefits of being able to use macros for sorting at some length.

Sure, it's a HUGE advantage compared to using variables and such. No debate at all from me there.

But I think in retrospect it's needlessly complex.

Given the small number of sort config variations in the style repo, and the fact that BibLaTeX (which is really well-designed, with features we don't have) has made due without that kind of complexity, seems to support that conclusion.

**Comment by fbennett** [comment]
No worries, I don't have strong feelings about future directions. I mainly
just wanted to point back to the text of the spec as a source of answers re
current CSL.

**Comment by bdarcus** [comment]
BTW, some very interesting discussion with the biblatex maintainer on the linked issue about sorting (and extended date-times).

https://github.com/bdarcus/csln/issues/64#issuecomment-1586134648

They do have ways to add new sorting configs via "sorting templates", but it sounds like the even more complicated stuff they've dealt with relates to multi-lingual requirements, where they actually allow people to change the name data model, and then in turn how sorting behaves.

**Comment by adam3smith** [comment]
> The examples they include seem to suggest pretty standard author-year?

No.

> Brown W and Peters P (2003)
> Brown W, Hughes J and Kent T (2003a)
